services:
  - type: web
    name: anniversary-2-years
    runtime: static
    buildCommand: pnpm install && pnpm run build
    publishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
